$(document).ready(function(){
  $("#button1").click(function(){
    $("#1").toggle();
    $("#question1").toggle();
  });
  $("#button2").click(function(){
    $("#2").toggle();
    $("#question2").toggle();
  });
  $("#button3").click(function(){
    $("#3").toggle();
    $("#question3").toggle();
  });
  $("#button4").click(function(){
    $("#4").toggle();
    $("#question4").toggle();
  });
  $("#button5").click(function(){
    $("#5").toggle();
    $("#question5").toggle();
  });
  $("#button6").click(function(){
    $("#6").toggle();
    $("#question6").toggle();
  });
  $("#button7").click(function(){
    $("#7").toggle();
    $("#question7").toggle();
  });
  $("#button8").click(function(){
    $("#8").toggle();
    $("#question8").toggle();
  });
  $("#button9").click(function(){
    $("#9").toggle();
    $("#question9").toggle();
  });
  $("#button10").click(function(){
    $("#10").toggle();
    $("#question10").toggle();
  });
  $("#button11").click(function(){
    $("#11").toggle();
    $("#question11").toggle();
  });
  $("#button12").click(function(){
    $("#12").toggle();
    $("#question12").toggle();
  });
  $("#button13").click(function(){
    $("#13").toggle();
    $("#question13").toggle();
  });
  $("#button14").click(function(){
    $("#14").toggle();
    $("#question14").toggle();
  });
  $("#button15").click(function(){
    $("#15").toggle();
    $("#question15").toggle();
  });
  $("#button16").click(function(){
    $("#16").toggle();
    $("#question16").toggle();
  });
  $("#button17").click(function(){
    $("#17").toggle();
    $("#question17").toggle();
  });
  $("#button18").click(function(){
    $("#18").toggle();
    $("#question18").toggle();
  });
  $("#button19").click(function(){
    $("#19").toggle();
    $("#question19").toggle();
  });
});
